### PR TITLE
fixed an issue with AbstractComboBox. The KeyEvent in processKeyEvent was not propagated to the super class

### PR DESCRIPTION
**Pull request by etsinko**

### CODE REVIEW

**Comment by caduandrade** [comment]
Hi Egor! Why do you need this? The event was not propagated to the super class to cancel the original popup JComboBox. Wihout that, KEY DOWN on CheckComboBox will not work. Perhaps the AbstractComboBox should not be public.

**Comment by etsinko** [comment]
Hello,
I found that in my case whenever a CheckComboBox was selected all the window hotkeys stopped working because AbstractComboBox would silently ignore them.

**Comment by etsinko** [comment]
Maybe this should be there instead:

``` java
    @Override
    public void processKeyEvent(KeyEvent e) {
      if (e.getKeyCode() == KeyEvent.VK_DOWN) {
        AbstractComboBox.this.setPopupVisible(true);
      }
      else {
            super.processKeyEvent(e);
      }
    }
```

This will only intercept VK_DOWN event and propagate all other ones.

**Comment by caduandrade** [comment]
I noticed that need add the "space" key code in the "if" too. Both keys
shows the popup.

What other hotkeys stopped work for you? Some default hotkey or a
customized hotkey? If is a customized, how did you set it? Using a
KeyListener or a InputMap?

tks for help!

2015-03-24 13:41 GMT-03:00 Egor Tsinko notifications@github.com:

**Comment by etsinko** [comment]
I'm only using `CheckComboBox` class so I can't say for other components of japura-gui. 

I install all needed actions with keystrokes (i.e. hotkeys) into an input map of the parent component. All of them work until CheckComboBox gets selected. Once it is selected pressing the hotkeys doesn't do anything.

I traced it to `AbstractComboBox.processKeyEvent()` and noticed that event gets generated once I press the hotkey but doesn't propagate to the superclass where it would be dispatched to a parent class. 

If you look into `JComboBox.processKeyEvent()` for example you'll notice that they propagate an event up to the superclass:

``` java
    /**
     * Handles <code>KeyEvent</code>s, looking for the Tab key.
     * If the Tab key is found, the popup window is closed.
     *
     * @param e  the <code>KeyEvent</code> containing the keyboard
     *          key that was pressed
     */
    public void processKeyEvent(KeyEvent e) {
        if ( e.getKeyCode() == KeyEvent.VK_TAB ) {
            hidePopup();
        }
        super.processKeyEvent(e);
    }
```

**Comment by caduandrade** [comment]
Egor, thanks for your help! I will take a look.

Sometimes extends Swing is not easy :-(

My first idea was just use the original JComboBox as a "dummy component" to
have the same paint and override the setPopupVisible, showPopup and
hidePopup methods to have my customized popup with checkboxes. Should be
easy but the Swing is bad because the JComboBox don't use these methods all
the times, it use the popup attribute.

Ex.: when you click on the component, no print for:

---

public static void main(String args[]) {
  MyCombo combo = new MyCombo();
  combo.addItem("test");

  JFrame frame = new JFrame();
  frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
  frame.add(combo);
  frame.pack();
  frame.setLocationRelativeTo(null);
  frame.setVisible(true);
}

public static class MyCombo extends JComboBox<String> {
  @Override
  public void setPopupVisible(boolean v) {
    System.out.println("setPopupVisible: " + v);
    super.setPopupVisible(v);
  }

  @Override
  public void showPopup() {
    System.out.println("showPopup");
    super.showPopup();
  }

## }

Now I have to rewrite the events to show/hide the popups too as this
processKeyEvent :-(

I will work on it with your suggestions.

2015-03-25 11:33 GMT-03:00 Egor Tsinko notifications@github.com:

**Comment by etsinko** [comment]
Yeah, I also find Swing clumsy. I prefer Qt. 
Thanks for your work!

**Pull request merged**
